
<footer class="footer_class">
	<div class="col">
		<div class="headr">Kirito</div>
		<div class="body">
			<p>A full service branding games for gamers</p>
			<p>Term of Service</p>
			<p>Privacy Policy</p>
			<p>© 2023 Kirito. All rights reserved.</p>
		</div>
	</div>
	<div class="col">
		<div class="headr">Get in touch</div>
		<div class="body">
			<p>Monday - Friday</p>
			<p>9:00 AM - 5:00 PM</p>
			<p>Contact</p>
			<p>Facebook</p>
			<p>Instagram</p>
		</div>
	</div>
	<div class="col">
		<div class="headr">Join our Mailing List</div>
		<div class="body">
			<form class="bodyform" action="./enquire.php">
				<input type="text" name="first_name" placeholder="First Name">
				<input type="email" name="email" placeholder="Email">
				<input type="submit" value="Submit">
			</form>
		</div>
	</div>
	<div class="col">
		<div class="headr">Explore</div>
		<div class="body">
			<a rel="noopener noreferrer" target="_blank" href="./index.php">Home</a>
			<a rel="noopener noreferrer" target="_blank" href="./product.php">Product</a>
			<a rel="noopener noreferrer" target="_blank" href="./payment.php">Enquire / Payment</a>
			<a rel="noopener noreferrer" target="_blank" href="./about.php">About</a>
			<a rel="noopener noreferrer" target="_blank" href="./enhancements.php">Enhancements</a>
			<a rel="noopener noreferrer" target="_blank" href="./enhancements2.php">(New!!) Enhancements 2</a>
		</div>
	</div>
</footer>