<header id="pro_home">
    <div class="heading pro_head">
        <div class="menu_bar">KIRITO</div>
        <nav>
            <a href="index.php" class="abc" id="enhancement2">Home</a>
            <a href="product.php" class="abc">Product</a>
            <a href="payment.php" class="abc">Payment</a>
            <a href="about.php" class="abc">About</a>
            <a href="enhancements.php" class="abc">Enhancements</a>
            <a href="more.php" class="abc abc_more">
                <svg class="more_menu_icon" xmlns="http://www.w3.org/2000/svg" fill="#fafafa" height="32" viewBox="0 96 960 960" width="32"><path d="M120 816v-60h720v60H120Zm0-210v-60h720v60H120Zm0-210v-60h720v60H120Z"/></svg>
            </a>
        </nav>
    </div>
</header>